services:
  pg:
    image: postgres:15-alpine
    container_name: orbis_am_tool_postgres
    env_file:
      - ./.env
    expose:
      - "5432"
    volumes:
      - orbis_am_tool_db:/var/lib/postgresql/data
  orbis_am_tool:
    build: .
    container_name: orbis_am_tool
    env_file:
      - ./.env
    expose:
      - "8000"
    restart: always
    depends_on:
      - pg
    volumes:
      - ./orbis_am_tool:/orbis_am_tool
      - ./nginx/static:${DJANGO_STATIC_ROOT}
  app:
    image: nginx:latest
    container_name: orbis_am_tool_app
    ports:
      - ${ORBIS_AM_TOOL_PORT}:80
      - 443:443
    volumes:
      - ./nginx/static:${DJANGO_STATIC_ROOT}:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ${NGINX_CERT_FILE}:/etc/ssl/certs/orbis.crt:ro;
      - ${NGINX_CERT_KEY}:/etc/ssl/private/orbis.key:ro;
      - ./logs:/var/log/nginx
    depends_on:
      - orbis_am_tool


volumes:
 orbis_am_tool_db:
